#!/usr/bin/env bash
set -e

me=$(basename ${0})

[[ $# -lt 2 ]] && {
    cat <<EOF >&2
Find the common parents of two refs

Usage: ${me/git-/git } REF1 REF2
EOF
    exit 1
}

REF1=${1}
REF2=${2}

comm --nocheck-order -1 -2 <(git rev-list --reverse --first-parent ${REF1}) <(git rev-list --reverse --first-parent ${REF2})
