#!/usr/bin/env bash
set -e

# from http://stackoverflow.com/questions/5143795/how-can-i-check-in-a-bash-script-if-my-local-git-repo-has-changes-or-not

if ! git diff-index --cached --quiet --ignore-submodules HEAD --
then
    exit 0
else
    exit 1
fi
