#!/usr/bin/env bash
set -e

[[ $# -lt 1 ]] && {
    cat <<EOF >&2
Rebase Github pull request on the current branch

Usage: ${me/git-/git } PR
EOF
    exit 1
}

PR=${1}

git checkout -b pr/${PR} pr/${PR}
git rebase @{-1}
git checkout @{-2}
git rebase @{-1}
