#!/usr/bin/env bash
set -e

# Show current branch's ticket
# Usage: ${me/git-/git }


STYLE=`git config --get branch.ticket`

[[ -z "${STYLE}" ]] && exit 0

BRANCH=`git rev-parse --abbrev-ref HEAD`
TICKET=`echo ${BRANCH} | grep --only-matching '[A-Z][_A-Z\-]\+[0-9]\+' | head -1 || echo ''`

if [[ "${STYLE}" == "jira" ]]; then
    [[ "${TICKET}" == "" ]] && exit 0
    echo ${TICKET}
elif [[ "${STYLE}" == "trac" ]]; then
    [[ "${TICKET}" == "" ]] && echo "no ticket" && exit 0
    TRAC=`echo ${TICKET} | sed 's/[^0-9]//g'`
    [[ -n "${TRAC}" ]] && TRAC="#${TRAC}" && echo ${TRAC}
fi
