#!/usr/bin/env bash
set -e

me=$(basename ${0})

[[ $# -lt 1 ]] && {
    cat <<EOF >&2
Delete tag

Usage: ${me/git-/git } TAG [--remote]
EOF
    exit 1
}

TAG=${1}
REMOTE=${2}

git tag -d ${TAG} || true

[[ ${REMOTE} == "--remote" ]] && {
    git push $(git branch-remote) :refs/tags/${TAG}
}
