#!/usr/bin/env bash
set -e

# Output submodule paths
# Usage: ${me/git-/git }

git .gitmodules | grep "path =" | sed "s,.*path = ,,"
# git config --list | grep "^submodule" | sed "s/^submodule\.//" | sed "s/\.url=.*//"
