#!/usr/bin/env bash
set -e

# Use GIT to fetch new branches/tags/heads
# Never use SVN to do that; it will start fetching every single revision

set +e
git changed &>/dev/null
code=$?
set -e
[[ $code != 0 ]] && git save
git pull
git svn rebase $@
[[ $code != 0 ]] && git pop
