#!/usr/bin/env bash
set -e

# Setup fetching Github pull-requests,
# optionally limit to only one pull-request.
# Usage: ${me/git-/git } [REMOTE [PR]]

REMOTE=${1:-origin}
PR=${2}

git config --get remote.${REMOTE}.fetch | grep -q "/pull/" || {
    git config --add remote.${REMOTE}.fetch "+refs/pull/*/head:refs/remotes/${REMOTE}/pr/*"
}

[[ -z ${PR} ]] || {
    REF=refs/pull/${PR}/head:refs/remotes/pr/${PR}
}

git fetch ${REMOTE} ${REF}
