#!/usr/bin/env bash
set -e

# Get the SVN revision of a GIT commit
# Usage: ${me/git-/git } [COMMIT]

COMMIT=${1:-"HEAD"}

# faster than git svn find-rev
git rev-list --format=%B --max-count=1 ${COMMIT} | grep 'git-svn-id' | sed "s|.*\@\([0-9]\+\).*|\1|"
