#!/usr/bin/env bash
set -e

# Fetch Github pull request(s)
# Usage: ${me/git-/git } [REMOTE [PR]]

REMOTE=${1}
PR=${2}

[[ ${REMOTE} =~ ^[0-9]+$ ] && {
    PR=${REMOTE}
    REMOTE=
}

[[ -z ${REMOTE} ]] || {
    REMOTE=$(git branch-tracker | cut -d "/" -f1)
    [[ -z ${REMOTE} ]] && echo >&2 "Remote required" && exit 1
}

git config --add remote.${REMOTE}.fetch "+refs/pull/*/head:refs/remotes/${REMOTE}/pr/*"
[[ -z ${PR} ]] || {
    git fetch ${REMOTE} refs/pull/${PR}/head:refs/remotes/pr/${PR}
} || {
    git fetch ${REMOTE}
}
