#!/usr/bin/env bash
set -e

# Show current branch's ticket
# Usage: ${me/git-/git }


STYLE=`git config --get branch.ticket`

[[ -z "${STYLE}" ]] && exit 0

BRANCH=`git rev-parse --abbrev-ref HEAD`
TICKET=`echo ${BRANCH} | sed 's/.*\([A-Za-z\-_]\+\)\([0-9]\+\)[\-_].*/\1-\2/g'`

if [[ "${STYLE}" == "jira" ]]; then
    [[ "${BRANCH}" == "${TICKET}" ]] && exit 0
    echo ${TICKET}
elif [[ "${STYLE}" == "trac" ]]; then
    [[ "${BRANCH}" == "${TICKET}" ]] && echo "no ticket" && exit 0
    TRAC=`echo ${TICKET} | sed 's/[^0-9]//g'`
    [[ -n "${TRAC}" ]] && TRAC="#${TRAC}" && echo ${TRAC}
fi
