#!/usr/bin/env bash
set -e

me=$(basename ${0})

[[ $# -lt 1 ]] && {
    cat <<EOF >&2
Rename branch

Usage: ${me/git-/git } NEW_BRANCH
Usage: ${me/git-/git } BRANCH NEW_BRANCH
EOF
    exit 1
}

BRANCH=${1}
NEW_BRANCH=${2}

git branch -m ${BRANCH} ${NEW_BRANCH}
