#!/usr/bin/env bash
set -e

# Output a branch's (default: current) tracker
# Usage: ${me/git-/git } [BRANCH]

BRANCH=${1}
# [[ -z ${BRANCH} ]] && BRANCH=$(git branch-name)

git rev-parse --abbrev-ref --symbolic-full-name ${BRANCH}@{u} 2>/dev/null | sed "s/@{u}//"
